apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: advanced-cluster-management
  namespace: open-cluster-management
spec:
  upgradeStrategy: Default
  targetNamespaces:
    - open-cluster-management
