apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gitops-policy-generator
policyDefaults:
  namespace: acm-policies
  remediationAction: enforce
placementBindingDefaults:
  name: "binding-policy-gitops"
policies:
  - name: policy-gitops-subscription
    remediationAction: enforce
    manifests:
      - path: manifests/gitops-subscription/
  - name: policy-gitops-instance
    configurationPolicyAnnotations:
      apps.open-cluster-management.io/reconcile-option: replace
    complianceType: "mustonlyhave"
    manifests:
      - path: manifests/gitops-instance/
  - name: policy-gitops-bootstrap
    manifests:
      - path: manifests/gitops-bootstrap/
policySets:
  - name: "gitops"
    description: "Policy for bootstrapping cluster with gitops"
    policies:
      - policy-gitops-subscription
      - policy-gitops-instance
      - policy-gitops-bootstrap
    generatePolicySetPlacement: false
    placement:
      name: placement-policy-gitops
