namespace: acm-policies

resources:
  - ../../components/acm/base/
  - ../../components/gitops/

images:
  - name: policy-generator-plugin
    newName: registry.redhat.io/rhacm2/multicluster-operators-subscription-rhel8
    newTag: v2.8.7-18
