apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  resourceTrackingMethod: annotation
  applicationSet: {}
  disableAdmin: true
  extraConfig:
    exec.enabled: "true"
    resource.respectRBAC: "normal"
    resource.ignoreResourceUpdatesEnabled: "true"
    resource.compareoptions: |
      ignoreAggregatedRoles: true
    ? resource.customizations.ignoreResourceUpdates.external-secrets.io_ExternalSecret
    : |
      jsonPointers:
      - /status/refreshTime
    ? resource.customizations.ignoreResourceUpdates.ocs.openshift.io_StorageCluster
    : |
      jsonPointers:
      - /status
      - /metadata/resourceVersion
    ? resource.customizations.ignoreResourceUpdates.ocs.openshift.io_StorageSystem
    : |
      jsonPointers:
      - /status
      - /metadata/resourceVersion
    resource.customizations.ignoreResourceUpdates.noobaa.io_Noobaa: |
      jsonPointers:
      - /status
      - /metadata/resourceVersion
    resource.customizations.ignoreResourceUpdates.noobaa.io_BackingStore: |
      jsonPointers:
      - /status
      - /metadata/resourceVersion
    accounts.admin: apiKey, login
  kustomizeBuildOptions: "--enable-helm --enable-alpha-plugins"
  controller:
    resources:
      limits:
        memory: 4Gi
      requests:
        cpu: 1000m
        memory: 3Gi
  monitoring:
    enabled: true
  sso:
    provider: Dex
    dex:
      openShiftOAuth: true
  repo:
    env:
      - name: KUSTOMIZE_PLUGIN_HOME
        value: /etc/kustomize/plugin
    initContainers:
      - args:
          - -c
          - cp /etc/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator/PolicyGenerator
            /policy-generator/PolicyGenerator
        command:
          - /bin/bash
        name: policy-generator-install
        image: policy-generator-plugin
        volumeMounts:
          - mountPath: /policy-generator
            name: policy-generator
    sidecarContainers:
      - name: setenv-cmp-plugin
        command: [/var/run/argocd/argocd-cmp-server]
        env:
          - name: KUSTOMIZE_PLUGIN_HOME
            value: /etc/kustomize/plugin
          - name: INFRASTRUCTURE_ID
            value: '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}'
          - name: CLUSTER_ID
            value: '{{ (lookup "config.openshift.io/v1" "ClusterVersion" "" "version").spec.clusterID }}'
          - name: CLUSTER_GITOPS_NAME
            value: '{{ fromClusterClaim "gitops" }}'
          - name: CLUSTER_NAME
            value: '{{ fromClusterClaim "name" }}'
          - name: SUB_DOMAIN
            value: '{{ (lookup "config.openshift.io/v1" "Ingress" "openshift-ingress" "cluster").spec.domain }}'
          - name: BASE_DOMAIN
            value: '{{ (lookup "config.openshift.io/v1" "DNS" "" "cluster").spec.baseDomain }}'
        image: quay.io/gnunn/tools:latest
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: tmp
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: plugin.yaml
            name: setenv-cmp-plugin
    volumeMounts:
      - mountPath: /etc/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator
        name: policy-generator
    volumes:
      - emptyDir: {}
        name: policy-generator
      - configMap:
          name: setenv-cmp-plugin
        name: setenv-cmp-plugin
    resources:
      limits:
        cpu: "1"
        memory: 1.5Gi
      requests:
        cpu: 250m
        memory: 768Mi
  redis:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
  server:
    insecure: true
    host: 'gitops.{{ (lookup "config.openshift.io/v1" "Ingress" "openshift-ingress" "cluster").spec.domain }}'
    route:
      enabled: true
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
  notifications:
    enabled: true
  resourceIgnoreDifferences:
    resourceIdentifiers:
      - group: route.openshift.io
        kind: Route
        customization:
          jsonPointers:
            - /status/ingress
            - /metadata/annotations
      - group: quay.redhat.com
        kind: QuayRegistry
        customization:
          jsonPointers:
            - /status/ingress
      - group: cluster.open-cluster-management.io
        kind: ManagedCluster
        customization:
          jsonPointers:
            - /spec/managedClusterClientConfigs
  resourceExclusions: |
    - apiGroups:
      - tekton.dev
      clusters:
      - '*'
      kinds:
      - TaskRun
      - PipelineRun
    - apiGroups:
      - operator.tekton.dev
      clusters:
      - '*'
      kinds:
      - TektonAddon
      - TektonInstallerSet
    - apiGroups:
      - compliance.openshift.io
      kinds:
      - ComplianceCheckResult
      - ComplianceRemediation
    - apiGroups:
      - policy.open-cluster-management.io
      kinds:
      - ConfigurationPolicy
    - apiGroups:
      - noobaa.io
      kinds:
      - NooBaa
      - BucketClass
  ha:
    enabled: false
  rbac:
    defaultPolicy: "role:none"
    policy: |
      p, role:none, *, *, */*, deny
      g, system:cluster-admins, role:admin
      g, cluster-admins, role:admin
    scopes: "[groups]"
