apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-gitops-operator
spec:
  config:
    env:
      - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
        value: openshift-gitops, gitops
      - name: CONTROLLER_CLUSTER_ROLE
        value: gitops-controller
      - name: SERVER_CLUSTER_ROLE
        value: gitops-server
      - name: DISABLE_DEFAULT_ARGOCD_INSTANCE
        value: "true"
  channel: latest
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
